owner: mozo-works
repo: upptime

sites:
  - name: Google
    url: https://www.google.com
  - name: Naver
    url: https://www.naver.com
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co
